version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    restart: always
    volumes:
      - db_store:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - '5432:5432'
    command: ['postgres', '-c', 'config_file=/etc/postgresql/postgresql.conf']

volumes:
  db_store:
