version: '3.8'

services:
  db:
    build: .
    container_name: postgres-db
    environment:
      POSTGRES_USER: ciro
      POSTGRES_PASSWORD: ciro0022
      POSTGRES_DB: system-watch-db
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf

volumes:
  pgdata:
