version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - '5422:5422'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      [
        'postgres',
        '-c',
        'wal_level=logical',
        '-c',
        'max_replication_slots=4',
        '-c',
        'max_wal_senders=4',
      ]
